name: Bug Report
description: Something went awry
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Need help or support?
        Please don't open an issue! Head to https://stackoverflow.com/questions/tagged/chart.js.
  
  - type: markdown
    attributes:
      value: "Bug reports MUST be submitted with an interactive example: https://codepen.io/pen?template=BapRepQ."

  - type: markdown
    attributes:
      value: Chart.js versions lower then 3.x are NOT supported anymore, new issues will be disregarded.

  - type: textarea
    attributes:
      label: Expected behavior
      description: Tell us what should happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current behavior
      description: Tell us what happens instead of the expected behavior.
    validations:
      required: true

  - type: input
    attributes:
      label: Reproducable sample
      description: |
        Please provide issue reproduction.
        You can use [this codepen](https://codepen.io/pen?template=BapRepQ) to make a reproducable sample.

        If filing a bug against `master`, you may reference the latest code via
        https://www.chartjs.org/dist/master/chart.min.js (changing the filename to
        point at the file you need as appropriate). Do not rely on these files for
        production purposes as they may be removed at any time.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Optional extra steps/info to reproduce

  - type: textarea
    attributes:
      label: Possible solution
      description: If you have suggestions on a fix for the bug.

  - type: textarea
    attributes:
      label: Context
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world.

  - type: input
    attributes:
      label: chart.js version
      description: Which version of `chart.js` are you using?
      placeholder: "v0.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Browser name and version

  - type: input
    attributes:
      label: Link to your project
